# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /mnt/c/MatriceAI/Deep_Fashion_Praneeth/data/yolov9_format # dataset root dir
train: /mnt/c/MatriceAI/Deep_Fashion_Praneeth/data/yolov9_format/train/images  # train images (relative to 'path') 4 images
val: /mnt/c/MatriceAI/Deep_Fashion_Praneeth/data/yolov9_format/val/images # val images (relative to 'path') 4 images
test: /mnt/c/MatriceAI/Deep_Fashion_Praneeth/data/yolov9_format/test/images # test images (optional)

# Classes (80 COCO classes)
names:
  0: short sleve top
  1: trousers

